// Bundles the service into dist/server.mjs: one file with every dependency, so the host needs only
// `node` to run it (storage uses node:sqlite, so there is no native module).
//
// The service has no npm project of its own. Its packages are in the web app's package.json, whose
// `npm run build` and `npm run dev` call this (see vite.config.ts); it also runs on its own:
//   node jiuwenswarm/extensions/blackboard/host/docservice/build.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
export const WEB_APP = resolve(here, '..', '..', '..', '..', 'channels', 'web', 'frontend')
export const BUNDLE = join(here, 'dist', 'server.mjs')

export const webAppRequire = createRequire(join(WEB_APP, 'package.json'))

// Bare imports resolve from the web app, as if the importing file were in it. Plugin code under
// extensions/ has no node_modules of its own.
export const resolveFromWebApp = {
  name: 'resolve-from-web-app',
  setup(b) {
    b.onResolve({ filter: /^[^./]/ }, async (args) => {
      if (args.pluginData?.again || args.kind === 'entry-point' || /^[a-z]+:/i.test(args.path)) return undefined
      const result = await b.resolve(args.path, { kind: args.kind, resolveDir: WEB_APP, pluginData: { again: true } })
      return result.errors.length ? undefined : result
    })
  },
}

export const NOTICES = join(here, 'dist', 'THIRD_PARTY_NOTICES.txt')

export async function buildDocService({ logLevel = 'warning' } = {}) {
  const { build } = webAppRequire('esbuild')
  const result = await build({
    entryPoints: [join(here, 'src', 'main.ts')],
    outfile: BUNDLE,
    absWorkingDir: here,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    plugins: [resolveFromWebApp],
    // Some bundled packages use require(); give the ESM bundle one.
    banner: { js: "import { createRequire as __bbRequire } from 'node:module'; const require = __bbRequire(import.meta.url);" },
    legalComments: 'none',
    metafile: true,
    logLevel,
  })
  writeFileSync(NOTICES, notices(bundledPackages(result.metafile)))
  return BUNDLE
}

// The npm packages that ended up in the bundle, from esbuild's list of inputs.
export function bundledPackages(metafile) {
  const found = new Map()
  for (const input of Object.keys(metafile.inputs)) {
    const path = input.replace(/\\/g, '/')
    let dir
    if (path.endsWith('vendor/y-tiptap-nodemarks.js')) {
      // The patched copy of @tiptap/y-tiptap (see scripts/make-ytiptap-nodemarks.mjs).
      dir = join(WEB_APP, 'node_modules', '@tiptap', 'y-tiptap')
    } else {
      const at = path.lastIndexOf('node_modules/')
      if (at < 0) continue
      const parts = path.slice(at + 'node_modules/'.length).split('/')
      dir = resolve(here, path.slice(0, at + 'node_modules/'.length) + parts.slice(0, parts[0].startsWith('@') ? 2 : 1).join('/'))
    }
    if (found.has(dir)) continue
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
    const licenseFile = readdirSync(dir).find((name) => /^licen[cs]e(\.|$)/i.test(name))
    found.set(dir, {
      name: pkg.name,
      version: pkg.version,
      license: typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? 'see license text',
      text: licenseFile ? readFileSync(join(dir, licenseFile), 'utf8').trim() : null,
    })
  }
  return [...found.values()].sort((a, b) => a.name.localeCompare(b.name))
}

function notices(packages) {
  const parts = [
    'Third-party software bundled in server.mjs, the Blackboard document service.',
    'Generated by build.mjs from the packages esbuild put in the bundle.',
  ]
  for (const p of packages) {
    parts.push(`==== ${p.name} ${p.version} (${p.license}) ====`, p.text ?? '(the package has no license file)')
  }
  return parts.join('\n\n') + '\n'
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await buildDocService({ logLevel: 'info' })
}
